FROM fedora

USER root

ENV GOPATH=/go

RUN  mkdir /go && chmod 755 /go && yum install -y git golang-bin && go get github.com/yudai/gotty && yum clean all && mkdir /workspace && chmod 777 workspace

RUN curl -sL -o /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux-s390x/oc.tar.gz && \
tar -C /tmp -xf /tmp/oc.tar.gz --no-same-owner && \
mv /tmp/oc /usr/local/bin && \
chmod +x /usr/local/bin/oc && \
rm /tmp/*

RUN cd /workspace && mkdir tkn-temp && cd tkn-temp && \
curl -LO https://github.com/tektoncd/cli/releases/download/v0.12.0/tkn_0.12.0_Linux_s390x.tar.gz && \
tar xvzf tkn_0.12.0_Linux_s390x.tar.gz && \
mv tkn /usr/local/bin && \
chmod u+x /usr/local/bin/tkn && cd .. && rm -rf tkn-temp

RUN curl -sL -o /usr/local/bin/odo https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-s390x && \
chmod +x /usr/local/bin/odo

RUN dnf -y install podman container-selinux --enablerepo updates-testing
RUN dnf -y install buildah container-selinux --enablerepo updates-testing
RUN dnf -y install skopeo container-selinux --enablerepo updates-testing

RUN \
    groupadd -g 1002 admin && useradd -u 1002 -g admin -G sudo -m -s /bin/bash admin && \
    sed -i /etc/sudoers -re 's/^%sudo.*/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' && \
    sed -i /etc/sudoers -re 's/^root.*/root ALL=(ALL:ALL) NOPASSWD: ALL/g' && \
    sed -i /etc/sudoers -re 's/^#includedir.*/## **Removed the include directive** ##"/g' && \
    echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "Customized the sudoers file for passwordless access to the admin user!" && \
    echo "admin user:";  su - admin -c id

RUN cd /workspace && git clone https://github.com/utherp0/workshop4

WORKDIR /workspace

EXPOSE 8080

USER admin

ENV HOME=/workspace

ENTRYPOINT ["/go/bin/gotty"]
CMD ["-w","bash"]
