apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: layer3
spec:
  host: layer3
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: layer3
spec:
  hosts:
  - layer3
  http:
  - route:
    - destination:
        host: layer3
        subset: v1
      weight: 50
    - destination:
        host: layer3
        subset: v2
      weight: 30
    - destination:
        host: layer3
        subset: v3
      weight: 20