=== Introduction

*This chapter will introduce the attendee to the concepts around the Role Based Access Control model integrated into OpenShift. This will cover the use of Users, Service Accounts and Permissions.*

NOTE: For the majority of this chapter the attendee will need to pair up with another. If the numbers are odd the presenter should fill the gap of the missing attendee - pair the attendees up before the chapter starts and get them to exchange numbers - your partner's username, and enter this whererever it says (PARTNERUSERNAME) below.

If you are not already logged on go to the UI URL {{OPENSHIFT_CONSOLE_URL}}[{{OPENSHIFT_CONSOLE_URL}}, window="_blank"] and logon as '{{USER_ID}}' and password openshift. 

If you do not already have a terminal tab running as defined in the pre-requisites please open one following the instructions in the pre-requisites

Ensure you are on the Administrator View (top level, select Administrator)

In the UI click on 'Home/Projects'

Click on 'Create Project'

Give the project a name of your choosing.

Display Name and Description are optional

Click on 'Create'

=== Giving Users permission

Click on `User Management/Role Bindings`

Click on `Create Binding`

Set `Name` to something that will make your project easily identifiable

Choose the ‘team[team number]’ in the Namespace pulldown

Select `admin` in the Role Name pull down

Ensure the Subject radiobox is set to ‘Group’

In the Subject Name enter the user name of your team (e.g. team1, team2, team3 etc.)

Click `Create`
